### ISSUE TITLE
Contracts can use Ownership only as a singleton, not multiple times

### ISSUE THREAD

**Issue by taitruong** [larry0x/cw-plus-plus#17]
@larry0x, Ownership is a const with a fixed key here:
https://github.com/larry0x/cw-plus-plus/blob/a5007575c6b698b5aeab5743439119bb9a987960/packages/ownable/src/lib.rs#L82

This means contracts may not be able to define multiple ownerships. One solution is defining an `OwnershipStore` with all functions like this:

```rust
pub struct OwnershipStore<'a, T: AddressLike> {
    item: Item<'a, Ownership<T>>,
}

impl<'a, T> OwnershipStore<'a, T>
where
    T: AddressLike,
{
    pub const fn new(key: &'a str) -> Self {
        Self {
            item: Item::new(key),
        }
    }

    pub fn initialize_owner()...

    pub fn get_ownership(storage: &dyn Storage)...


}
```

This way contract may define in their state, something like this:
```rust
pub const OWNERSHIP: OwnershipStore<Addr> = OwnershipStore::new("main-owner");
pub const SOME_OTHER_OWNERSHIP: OwnershipStore<Addr> = OwnershipStore::new("secondary-owner");
```

Also there might be cases where functions like `is_owner()`, `assert_owner()` might be used and in addition ownership info is required, like for response. Rn, this requires multiples calls with loading ownership from store.

If `Ownership` would implement these functions, no additional loads would be required.

**Comment by larry0x** [comment]
The design you pointed out is intentional.

An objective of this library is to establish a standardized way of managing ownership among contracts. To achieve this, we need to define a storage key that's consistent among all contracts. This is similar to how `cw2` and Ethereum's `Ownable` library work.

If you wish to use a non-standard ownership model, it may be better to fork this library, and also use a different storage key from `b"ownership"` to avoid confusion.
